language: node_js
node_js:
  - stable
cache:
  directories:
  - node_modules
before_install:
  # Decrypt credentials
  - openssl aes-256-cbc -K $encrypted_e45b403305bf_key -iv $encrypted_e45b403305bf_iv
    -in credentials.tar.gz.enc -out credentials.tar.gz -d

  # check gcloud-sdk
  - gcloud version || true

  # Authenticate with service account credentials
  - tar -xzf credentials.tar.gz
  - gcloud auth activate-service-account --key-file fresh-service.json

  - chmod a+x ./scripts/install.sh
  - chmod a+x ./scripts/deploy-container.sh
install:
  - npm install create-react-app
  - ./scripts/install.sh
script:
  - npm test
  - npm run build
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PWD
  - docker-compose build
  - docker push wisatong/freshwater
  - ./scripts/deploy-container.sh
